make the model of sponsor
solawi-projects/baum-bauer-backend pull request #2
Opened 2023-10-30 14:11 UTC by Shaqayeq-taheri

the Schema of the Sponsor is done

2023-10-30 14:20 UTC, Chandu-Sasidharan commented
@Shaqayeq-taheri Happy to see you all started working! In the the schema, lets make the email a unique field, so there won't be two entries with the same email

email: { type: String, required: true, unique: true }

2023-10-30 14:20 UTC, Chandu-Sasidharan approved these changes

2023-10-31 23:08 UTC, coderahmadi requested changes
@Shaqayeq-taheri, thanks great job. there are a few points that I need to mention.
1. Inside SponsorController.js line #2. with Model imported .js extension is required(Sponsor.js).
2. Inside SponsorController.js line #60, because you have used patch method, it means you are going to update an specific property so, the field name should be place (req.body.fieldName).

2023-11-02 13:05 UTC, Chandu-Sasidharan commented
@Shaqayeq-taheri  All looking good to me except for that email field in the Model. I am not sure how you guys are planning to use this collection, but if it is meant to store the unique list of sponsors, then its a good idea to make the email field unique to prevent any potential data inconsistencies

2023-11-06 08:32 UTC, coderahmadi approved these changes

2023-11-06 14:06 UTC, merged